DROP TABLE IF EXISTS authors;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS books;
CREATE TABLE authors (
auth_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname VARCHAR(255),
lastname VARCHAR(255),
secondaryname VARCHAR(255)
);
CREATE TABLE genres (
gen_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255)
);
CREATE TABLE books(
    book_id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    id_author BIGINT,
    FOREIGN KEY(id_author) REFERENCES authors(auth_id),
    id_genre BIGINT,
    FOREIGN KEY(id_genre) REFERENCES genres(gen_id)
);
