DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY, FIRSTNAME VARCHAR(255), LASTNAME VARCHAR(255), SECONDARYNAME VARCHAR(255));
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255),
    ID_AUTHOR BIGINT,
    FOREIGN KEY(ID_AUTHOR) REFERENCES AUTHORS(ID),
    ID_GENRE BIGINT,
    FOREIGN KEY(ID_GENRE) REFERENCES GENRES(ID)
);
